### PR TITLE
NameLayer fixes

### PR DESCRIPTION
**Pull request by Protonull**

### CODE REVIEW

**Comment by Maxopoly** [comment]
Why does this include undoing https://github.com/CivClassic/NameLayer/commit/1a25dbf42b784aa3f38462ef979ae3e42c5c7d60 to readd the Mercury dependency?

**Comment by Maxopoly** [comment]
Also I'm fine with merging this, but think we might want to diverge entirely for the 1.14 branch then instead of merging it later on

**Comment by Protonull** [comment]
Mercury APIs are present within the following files:-

 * command/commands/* (pretty much every command)
 * gui/AdminFunctionsGUI
 * gui/InvitationGUI
 * gui/MainGroupGUI
 * group/AutoAcceptHandler
 * group/Blacklist
 * group/Group
 * listeners/MercuryMessageListener
 * misc/Mercury
 * permission/GroupPermission
 * GroupManager
 * NameLayerPlugin

It felt like too big of a change to make, to remove all this based off of Teal removing just the dependency. I felt it better to re-add it, if only so that it'll compile, then deciding where to go from there if it became an issue.

As for this pull request, it doesn't have anything to do with the 1.14 update, but just to fix some glaring issues with what's currently running on the server :)

**Comment by ProgrammerDan** [comment]
I thought I already did all the work to remove mercury. Why are you starting from a branch before that effort? it was in with the 1.12 updates or 1.13 start, I forget which.

**Comment by Protonull** [comment]
Because there's a problem that needs to be imminently fixed on Civclassics and this is the master branch for the Civclassics fork? If there's a 1.12 version out there in the ether that has already fixed these things... that's great... but why hasn't that been reflected here... and more important, why isn't that being used on the server then? I can remove all the Mercury stuff if it's really that important, but I'd really, *really* like the fix the whole one player being able to lag the entire server with one command/gui click because the server is waiting for the database to delete an entry from the database.

**Comment by ProgrammerDan** [comment]
Idk why civclassic does what it does.

**Comment by Protonull** [comment]
So what should be the next move?

**Comment by ProgrammerDan** [comment]
Probably contribute the fixes as a patch (without re-adding mercury), once to master (and let Maxopoly deal with the compile problems) -- and second as a patch to civ14 branch, which iirc includes the full mercury removal (and should be 1.12 ... if the civmodcore api calls are still compatible with the 1.12 civmodcore)

Or yeah, just contribute this same effort (which seems great, btw) as a patch that does not re-add the mercury deps, to master, and don't worry about the build problem that you would experience locally.

**Comment by Protonull** [comment]
Oke, I'll work on removing Mercury

**Comment by Protonull** [comment]
Done and tested, everything seems in working order

**Comment by ProgrammerDan** [comment]
huh, ok. My comments were meant to encourage you not to worry about removing those code lines since they were already removed in the pending civ14 branch, but hey! looks good. Enjoy, @Maxopoly :)

**Comment by Maxopoly** [comment]
> Idk why civclassic does what it does.

Me neither tbh

**Comment by Maxopoly** [comment]
Staged and will be deployed with next restart

**Pull request merged**
